"""Negotiation intelligence.

Deterministic history reconstruction from the deal's offers, offer versions,
and negotiation events. Concessions are only reported when both directions of a
term change are known. The narrative summary is generated by the model provider
from these validated facts.
"""

from __future__ import annotations

from datetime import datetime

from app.models.base import ModelProvider
from app.schemas.context import (
    DealIntelligenceContext,
    OfferContextInfo,
)
from app.schemas.output import NegotiationConcession, NegotiationSummary

CONCESSION_FIELDS = ("amount", "price")


def _delta_description(before: OfferContextInfo, after: OfferContextInfo) -> str:
    if after.amount is not None and before.amount is not None:
        try:
            b = float(after.amount) - float(before.amount)
            return "increased" if b > 0 else "decreased" if b < 0 else "unchanged"
        except ValueError:
            return "changed"
    return "changed"


def _changes_between(
    before: OfferContextInfo, after: OfferContextInfo
) -> list[str]:
    changed: list[str] = []
    for field in CONCESSION_FIELDS + ("currency", "settlement_date", "expires_at"):
        b = getattr(before, field, None)
        a = getattr(after, field, None)
        if b != a:
            changed.append(field)
    return changed


def _concessions(
    offers: list[OfferContextInfo],
) -> list[NegotiationConcession]:
    if len(offers) < 2:
        return []
    ordered = sorted(offers, key=lambda o: (o.submitted_at or o.created_at, o.created_at))
    concession_rows: list[NegotiationConcession] = []
    for field in CONCESSION_FIELDS:
        prev = next((o for o in ordered if getattr(o, field) is not None), None)
        curr = next(
            (
                o
                for o in reversed(ordered)
                if getattr(o, field) is not None
            ),
            None,
        )
        if prev is None or curr is None or prev.id == curr.id:
            continue
        concession_rows.append(
            NegotiationConcession(
                field=field,
                from_value=str(getattr(prev, field)),
                to_value=str(getattr(curr, field)),
                direction=_delta_description(prev, curr),
            )
        )
    return concession_rows


def _total_offers(context: DealIntelligenceContext) -> int:
    return len(context.offers)


def compute_negotiation_summary(
    context: DealIntelligenceContext,
    provider: ModelProvider,
) -> NegotiationSummary:
    offers = [
        o for o in context.offers if o.status in ("SUBMITTED", "COUNTERED", "ACCEPTED")
    ]
    if not offers:
        narrative = provider.generate_negotiation_summary(context, {})
        return NegotiationSummary(
            summary=narrative,
            major_concessions=[],
            changed_terms=[],
            unresolved_points=[],
            latest_counterparty_position="",
            timeline=[],
            possible_blockers=[],
        )

    ordered = sorted(
        offers, key=lambda o: (o.submitted_at or o.created_at, o.created_at)
    )
    concessions = _concessions(ordered)
    changed_terms: list[str] = []
    for i in range(1, len(ordered)):
        changed_terms.extend(_changes_between(ordered[i - 1], ordered[i]))
    changed_terms = _dedupe(changed_terms)

    latest = ordered[-1]
    timeline = [
        f"{_fmt_date(o.submitted_at or o.created_at)} {o.status} "
        f"amount={o.amount or 'n/a'} {o.currency}"
        for o in ordered
    ]

    facts = {
        "total_offers": len(ordered),
        "concessions": [
            c.model_dump() for c in concessions
        ],
        "changed_terms": changed_terms,
    }
    narrative = provider.generate_negotiation_summary(context, facts)
    latest_pos = (
        f"Latest offer amount is {latest.amount or 'n/a'} "
        f"{latest.currency}."
    )

    possible_blockers: list[str] = []
    if latest.expires_at is not None:
        possible_blockers.append(
            f"Latest offer expires {latest.expires_at.date().isoformat()}."
        )

    return NegotiationSummary(
        summary=narrative,
        major_concessions=concessions,
        changed_terms=changed_terms,
        unresolved_points=[],
        latest_counterparty_position=latest_pos,
        timeline=timeline,
        possible_blockers=possible_blockers,
    )


def _fmt_date(value: datetime) -> str:
    return value.date().isoformat() if value is not None else "unknown-date"


def _dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for v in values:
        if v not in seen:
            seen.add(v)
            out.append(v)
    return out