import type { Prisma, PrismaClient } from "@prisma/client";
import { prisma } from "../../lib/prisma.js";

/**
 * Security-relevant events (authentication + organization). This is the
 * durable audit trail the future financial audit pipeline reads.
 *
 * Rules:
 *  - NEVER store passwords, raw tokens, or token hashes.
 *  - metadata holds only safe, descriptive fields (emails, ids, reasons).
 *  - Organization events carry organizationId so events are tenant-scoped.
 */
export const SecurityEventType = {
  // Authentication (Phase 2)
  USER_REGISTERED: "USER_REGISTERED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  LOGOUT_ALL: "LOGOUT_ALL",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  EMAIL_VERIFICATION_REQUESTED: "EMAIL_VERIFICATION_REQUESTED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  SESSION_REVOKED: "SESSION_REVOKED",
  SESSION_EXPIRED: "SESSION_EXPIRED",

  // Organization (Phase 3)
  ORGANIZATION_CREATED: "ORGANIZATION_CREATED",
  ORGANIZATION_UPDATED: "ORGANIZATION_UPDATED",
  MEMBER_INVITED: "MEMBER_INVITED",
  MEMBER_INVITATION_REVOKED: "MEMBER_INVITATION_REVOKED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  MEMBER_SUSPENDED: "MEMBER_SUSPENDED",
  MEMBER_REACTIVATED: "MEMBER_REACTIVATED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  OWNERSHIP_TRANSFERRED: "OWNERSHIP_TRANSFERRED",

  // Deals (Phase 4)
  DEAL_CREATED: "DEAL_CREATED",
  DEAL_UPDATED: "DEAL_UPDATED",
  DEAL_STATE_CHANGED: "DEAL_STATE_CHANGED",
  DEAL_CANCELLED: "DEAL_CANCELLED",
  DEAL_EXPIRED: "DEAL_EXPIRED",

  // Counterparties & negotiation (Phase 5)
  COUNTERPARTY_CREATED: "COUNTERPARTY_CREATED",
  COUNTERPARTY_UPDATED: "COUNTERPARTY_UPDATED",
  COUNTERPARTY_VERIFICATION_CHANGED: "COUNTERPARTY_VERIFICATION_CHANGED",
  COUNTERPARTY_REVOKED: "COUNTERPARTY_REVOKED",
  DEAL_PARTICIPANT_INVITED: "DEAL_PARTICIPANT_INVITED",
  DEAL_PARTICIPANT_INVITATION_REVOKED: "DEAL_PARTICIPANT_INVITATION_REVOKED",
  DEAL_PARTICIPANT_JOINED: "DEAL_PARTICIPANT_JOINED",
  DEAL_PARTICIPANT_DECLINED: "DEAL_PARTICIPANT_DECLINED",
  DEAL_PARTICIPANT_SUSPENDED: "DEAL_PARTICIPANT_SUSPENDED",
  DEAL_PARTICIPANT_REACTIVATED: "DEAL_PARTICIPANT_REACTIVATED",
  DEAL_PARTICIPANT_REMOVED: "DEAL_PARTICIPANT_REMOVED",
  OFFER_CREATED: "OFFER_CREATED",
  OFFER_SUBMITTED: "OFFER_SUBMITTED",
  OFFER_COUNTERED: "OFFER_COUNTERED",
  OFFER_ACCEPTED: "OFFER_ACCEPTED",
  OFFER_REJECTED: "OFFER_REJECTED",
  OFFER_WITHDRAWN: "OFFER_WITHDRAWN",
  OFFER_EXPIRED: "OFFER_EXPIRED",
  OFFER_SUPERSEDED: "OFFER_SUPERSEDED",

  // Documents & requirements (Phase 6)
  DOCUMENT_CREATED: "DOCUMENT_CREATED",
  DOCUMENT_UPLOAD_RECEIVED: "DOCUMENT_UPLOAD_RECEIVED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_SUBMITTED: "DOCUMENT_SUBMITTED",
  DOCUMENT_UNDER_REVIEW: "DOCUMENT_UNDER_REVIEW",
  DOCUMENT_ACCEPTED: "DOCUMENT_ACCEPTED",
  DOCUMENT_REJECTED: "DOCUMENT_REJECTED",
  DOCUMENT_WITHDRAWN: "DOCUMENT_WITHDRAWN",
  DOCUMENT_REPLACED: "DOCUMENT_REPLACED",
  DOCUMENT_SUPERSEDED: "DOCUMENT_SUPERSEDED",
  DOCUMENT_EXPIRED: "DOCUMENT_EXPIRED",
  DOCUMENT_DOWNLOAD_REQUESTED: "DOCUMENT_DOWNLOAD_REQUESTED",
  REQUIREMENT_CREATED: "REQUIREMENT_CREATED",
  REQUIREMENT_SUBMITTED: "REQUIREMENT_SUBMITTED",
  REQUIREMENT_REJECTED: "REQUIREMENT_REJECTED",
  REQUIREMENT_WAIVED: "REQUIREMENT_WAIVED",
  REQUIREMENT_REOPENED: "REQUIREMENT_REOPENED",
  REQUIREMENT_SATISFIED: "REQUIREMENT_SATISFIED",
  REQUIREMENT_EXPIRED: "REQUIREMENT_EXPIRED",
  REQUIREMENT_DOCUMENT_ATTACHED: "REQUIREMENT_DOCUMENT_ATTACHED",

  // Approval Engine (Phase 7)
  APPROVAL_POLICY_CREATED: "APPROVAL_POLICY_CREATED",
  APPROVAL_POLICY_UPDATED: "APPROVAL_POLICY_UPDATED",
  APPROVAL_POLICY_ACTIVATED: "APPROVAL_POLICY_ACTIVATED",
  APPROVAL_POLICY_DEACTIVATED: "APPROVAL_POLICY_DEACTIVATED",
  APPROVAL_POLICY_ARCHIVED: "APPROVAL_POLICY_ARCHIVED",

  APPROVAL_WORKFLOW_CREATED: "APPROVAL_WORKFLOW_CREATED",
  APPROVAL_WORKFLOW_STARTED: "APPROVAL_WORKFLOW_STARTED",
  APPROVAL_WORKFLOW_APPROVED: "APPROVAL_WORKFLOW_APPROVED",
  APPROVAL_WORKFLOW_REJECTED: "APPROVAL_WORKFLOW_REJECTED",
  APPROVAL_WORKFLOW_EXPIRED: "APPROVAL_WORKFLOW_EXPIRED",
  APPROVAL_WORKFLOW_CANCELLED: "APPROVAL_WORKFLOW_CANCELLED",

  APPROVAL_REQUEST_CREATED: "APPROVAL_REQUEST_CREATED",
  APPROVAL_REQUEST_ASSIGNED: "APPROVAL_REQUEST_ASSIGNED",
  APPROVAL_REQUEST_APPROVED: "APPROVAL_REQUEST_APPROVED",
  APPROVAL_REQUEST_REJECTED: "APPROVAL_REQUEST_REJECTED",
  APPROVAL_REQUEST_ESCALATED: "APPROVAL_REQUEST_ESCALATED",
  APPROVAL_REQUEST_EXPIRED: "APPROVAL_REQUEST_EXPIRED",
  APPROVAL_REQUEST_CANCELLED: "APPROVAL_REQUEST_CANCELLED",

  APPROVAL_INVALIDATED: "APPROVAL_INVALIDATED",
  REAPPROVAL_REQUIRED: "REAPPROVAL_REQUIRED",

  // Settlement & Reconciliation (Phase 8)
  SETTLEMENT_CREATED: "SETTLEMENT_CREATED",
  SETTLEMENT_SUBMITTED: "SETTLEMENT_SUBMITTED",
  SETTLEMENT_STATUS_CHANGED: "SETTLEMENT_STATUS_CHANGED",
  SETTLEMENT_FAILED: "SETTLEMENT_FAILED",
  SETTLEMENT_CANCELLED: "SETTLEMENT_CANCELLED",
  SETTLEMENT_COMPLETED: "SETTLEMENT_COMPLETED",

  RECONCILIATION_STARTED: "RECONCILIATION_STARTED",
  RECONCILIATION_MATCHED: "RECONCILIATION_MATCHED",
  RECONCILIATION_MISMATCHED: "RECONCILIATION_MISMATCHED",
  RECONCILIATION_FAILED: "RECONCILIATION_FAILED",
  RECONCILIATION_RESOLVED: "RECONCILIATION_RESOLVED",

  // Deal Intelligence (Phase 9)
  DEAL_INTELLIGENCE_REQUESTED: "DEAL_INTELLIGENCE_REQUESTED",
  DEAL_INTELLIGENCE_COMPLETED: "DEAL_INTELLIGENCE_COMPLETED",
  DEAL_INTELLIGENCE_FAILED: "DEAL_INTELLIGENCE_FAILED",
  DEAL_INTELLIGENCE_QUERIED: "DEAL_INTELLIGENCE_QUERIED",

  // Quantum Optimization (Phase 10)
  DEAL_OPTIMIZATION_REQUESTED: "DEAL_OPTIMIZATION_REQUESTED",
  DEAL_OPTIMIZATION_COMPLETED: "DEAL_OPTIMIZATION_COMPLETED",
  DEAL_OPTIMIZATION_FAILED: "DEAL_OPTIMIZATION_FAILED",

  // OneSwap Integration (Phase 11)
  ONESWAP_QUOTE_FETCHED: "ONESWAP_QUOTE_FETCHED",
  ONESWAP_SWAP_INITIATED: "ONESWAP_SWAP_INITIATED",
  ONESWAP_SWAP_COMPLETED: "ONESWAP_SWAP_COMPLETED",
  ONESWAP_SWAP_FAILED: "ONESWAP_SWAP_FAILED",
  ONESWAP_SWAP_CANCELLED: "ONESWAP_SWAP_CANCELLED",
  ONESWAP_SWAP_DEPOSIT_RECORDED: "ONESWAP_SWAP_DEPOSIT_RECORDED",
  ONESWAP_LIQUIDITY_ADDED: "ONESWAP_LIQUIDITY_ADDED",
  ONESWAP_LIQUIDITY_REMOVED: "ONESWAP_LIQUIDITY_REMOVED",
  ONESWAP_POOL_QUERIED: "ONESWAP_POOL_QUERIED",
  ONESWAP_POOL_TICKER_QUERIED: "ONESWAP_POOL_TICKER_QUERIED",

  // Canton / Metatarz wallet (Phase 11)
  CANTON_WALLET_TRANSFER_SUBMITTED: "CANTON_WALLET_TRANSFER_SUBMITTED",
} as const;

export type SecurityEventTypeValue =
  (typeof SecurityEventType)[keyof typeof SecurityEventType];

export interface SecurityEventInput {
  type: SecurityEventTypeValue;
  userId?: string;
  organizationId?: string;
  metadata?: Record<string, unknown>;
  ipAddress?: string | null;
  userAgent?: string | null;
}

type LoggerLike = Pick<ReturnType<typeof getNoopLogger>, "error">;

function getNoopLogger() {
  return { error: (..._args: unknown[]) => undefined };
}

type Db = PrismaClient | Prisma.TransactionClient;

/**
 * Writes a security event with the given client (so it can join the caller's
 * transaction and roll back with it). Throws on failure — use only inside
 * transactions where the event must be durable together with the operation.
 */
export async function writeSecurityEvent(
  client: Db,
  input: SecurityEventInput,
): Promise<void> {
  await client.securityEvent.create({
    data: {
      type: input.type,
      userId: input.userId ?? null,
      organizationId: input.organizationId ?? null,
      metadata: input.metadata ? (input.metadata as object) : undefined,
      ipAddress: input.ipAddress ?? null,
      userAgent: input.userAgent ?? null,
    },
  });
}

/**
 * Persists a security event using the shared client. Wrap failures in
 * try/catch: security-event recording must never break the primary request
 * flow (use `writeSecurityEvent` instead when the event must be transactional).
 */
export async function recordSecurityEvent(
  input: SecurityEventInput,
  logger?: LoggerLike,
): Promise<void> {
  try {
    await prisma.securityEvent.create({
      data: {
        type: input.type,
        userId: input.userId ?? null,
        organizationId: input.organizationId ?? null,
        metadata: input.metadata ? (input.metadata as object) : undefined,
        ipAddress: input.ipAddress ?? null,
        userAgent: input.userAgent ?? null,
      },
    });
  } catch (err) {
    (logger ?? getNoopLogger()).error?.(
      { err, type: input.type },
      "security event failed",
    );
  }
}
